CardapioWEB_Demo/Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardapioWEB_Demo.Models
{
    [Table("Lanches")]
    public class Lanche
    {
        [Key]
        public int lancheID { get; set; }
        [Required(ErrorMessage = "O nome do lanche deve ser informado")]
   
        [Display(Name = "Nome do lanche")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "A descrição do lanche deve ser informado")]
        [Display(Name = "Descrição do lanche")]
        [MinLength(5, ErrorMessage = " Descrição deve tetr no minimo {1} caracteres")]
        public string DescricaoCurta { get; set; }
        [Required(ErrorMessage = "A descrição do lanche deve ser informado")]
        [Display(Name = "Descrição do lanche")]
        [MinLength(20, ErrorMessage = " Descrição deve tetr no minimo {1} caracteres")]
        [MaxLength(200, ErrorMessage = "Descrição deve ter no máximo {1} caracteres")]
        public string DescricaoDetalhada { get; set; }
        [Required(ErrorMessage = "Informe o preço do lanche")]
        [Display(Name = "Preco")]
        [Column(TypeName = "decimal(10,2)")]
        [Range(1, 999.99, ErrorMessage = "O preço deve estar entre 1 e 999,99")]
        public decimal Preco { get; set; }
        [Display(Name = "Caminho Imagem Normal")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1} caracteres")]
        public string ImageUrl { get; set; }
        [Display(Name = "Caminho Imagem Miniatura")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1} caracteres")]
        public string ImagemThumbnailUrl { get; set; }
        [Display(Name = "Preferido?")]
        public bool IsLanchePreferido { get; set; }
        [Display(Name = "Estoque")]
        public bool EmEstoque { get; set; }

        //Definir relacionamento entre lanche e categoria
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

CardapioWEB_Demo/Controllers/LancheController.cs
using CardapioWEB_Demo.Models;
using CardapioWEB_Demo.Repositories.Interfaces;
using CardapioWEB_Demo.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CardapioWEB_Demo.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.lancheID);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                //if (string.Equals("Normal", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    lanches = _lancheRepository.Lanches
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Normal"))
                //        .OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    lanches = _lancheRepository.Lanches
                //       .Where(l => l.Categoria.CategoriaNome.Equals("Natural"))
                //       .OrderBy(l => l.Nome);
                //}


                lanches = _lancheRepository.Lanches
                          .Where(l => l.Categoria.Nome.Equals(categoria))
                          .OrderBy(c => c.Nome);
            
                categoriaAtual = categoria;
            }

            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);
        }
        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.lancheID == lancheId);
            return View(lanche);
        }
        public ViewResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.lancheID);
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches
                          .Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));

                if (lanches.Any())
                    categoriaAtual = "Lanches";
                else
                    categoriaAtual = "Nenhum lanche foi encontrado";
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            });
        }

    }
}

CardapioWEB_Demo/Views/Lanche/Details.cshtml
@model Lanche
<div class="container">
    <div class="row">
        <div class="card">
            <div class="text-center">
                <img src="@Model.ImageUrl" class="img-fluid" alt="">
            </div>
            <div class="card-block">
                <h2 class="card-title">@Model.Nome</h2>
                <p class="card-text"><h5>@Model.DescricaoDetalhada</h5></p>
                <p class="btn btn-group align-content-lg-end">
                    <a asp-controller="Lanche" asp-action="List"
                       class="btn btn-outline-info">Ver todos os lanches</a>
                    <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra"
                       asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheId="@Model.lancheID">
                        Adicionar @Model.Nome ao carrinho
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

CardapioWEB_Demo/Views/Lanche/List.cshtml
@model LancheListViewModel

<h2>@Model.CategoriaAtual</h2>

<div class="row">
    @foreach (Lanche lanche in Model.Lanches)
    {
        @*@Html.Partial("_LanchesResumo", lanche)*@
        <partial name="_LanchesResumo" for="@lanche" />
    }
</div>